### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by TehMaxwell** [uoseeesoc/eeesoc.com#1]
## Introduction

The main title page for the society website. Contains links to other pages on the website as well as social media links.

## Task List

- [ ] Membership Button ==> Links too SU website membership ticket page
- [ ] Upcoming Events Button ==> Links too Facebook Events page
- [ ] About Button ==> Links a separate about page on the website
- [ ] Social Media Buttons ==> Links to the separate social media pages of the Society (Facebook, Twitter, Instagram, Snapchat)
